//* Async actions
export const FETCH_CVES_REQUEST = 'FETCH_CVES_REQUEST';
export const FETCH_CVES_SUCCESS = 'FETCH_CVES_SUCCESS';
export const FETCH_CVES_FAILURE = 'FETCH_CVES_FAILURE';

export const FETCH_YEARS_REQUEST = 'FETCH_YEARS_REQUEST';
export const FETCH_YEARS_SUCCESS = 'FETCH_YEARS_SUCCESS';
export const FETCH_YEARS_FAILURE = 'FETCH_YEARS_FAILURE';
//

//* Sync actions
export const SELECT_YEAR = 'SELECT_YEAR';
export const SEARCH_BY_ID = 'SEARCH_BY_ID';
export const RESET_SEARCH = 'RESET_SEARCH';

export const TOGGLE_MINOR_DATA = 'TOGGLE_MINOR_DATA';
export const TOGGLE_MAJOR_DATA = 'TOGGLE_MAJOR_DATA';
export const TOGGLE_CRITICAL_DATA = 'TOGGLE_CRITICAL_DATA';

export const RESET_ALL = 'RESET_ALL';
//
